services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.ml.enabled=false
    ports:
      - '9200:9200'
    healthcheck:
      test: curl -s http://localhost:9200/_cluster/health | grep -vq '\"status\":\"red\"'
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - es_data:/usr/share/elasticsearch/data

volumes:
  es_data:
